remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Those Who Soar
description: |
  Team #1: Carter Webb, Andrew Kalb, and Gavin Casper. \n
  Instructors: Dave Feil-Seifer, Devrin Lee, and Sara Davis with the Department of CSE \n
  External Advisor: Eelke Folmer with the Department of CSE \n
  CS 426 Senior Project in Computer Science, Spring 2024, at UNR, CSE Department \n
